#!/bin/bash
if [ "x$COVERAGE" == "xyes" ]; then
  pip install --user gcovr
  pip install --user cpp-coveralls
else
  echo "no dependencies to install"
fi

if [ "x$AUTOTOOLS" == "xyes" ]; then
  AUTOTOOLS=yes

  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository -y ppa:rbose-debianizer/automake &> /dev/null
    sudo apt-get -qq update
    sudo apt-get -qq install automake
  fi

  # https://github.com/sass/libsass/pull/2183
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew uninstall libtool
    brew install libtool
  fi
fi
