#!/bin/bash

script/branding

if [ ! -d "sass-spec" ]; then
  if [ -z "$SASS_SPEC_REPO" ]; then
    SASS_SPEC_REPO=https://github.com/sass/sass-spec.git
  fi
  git clone $SASS_SPEC_REPO
fi
if [ ! -d "sassc" ]; then
  git clone https://github.com/sass/sassc.git
fi
