#!/bin/bash

set -e

script/bootstrap

# export this path right here (was in script/spec before)
export SASS_LIBSASS_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../ && pwd )"

# use some defaults if not running under travis ci
if [ "x$TRAVIS_BUILD_DIR" == "x" ]; then export TRAVIS_BUILD_DIR=$(pwd)/build; fi
if [ "x$SASS_SASSC_PATH" == "x" ]; then export SASS_SASSC_PATH=$(pwd)/sassc; fi
if [ "x$SASS_SPEC_PATH" == "x" ]; then export SASS_SPEC_PATH=$(pwd)/sass-spec; fi

if [ "x$CXX" == "xclang++" ]; then
  COVERAGE="--enable-coverage"
  export EXTRA_CFLAGS="-O0 --coverage"
  export EXTRA_LDFLAGS="-O0 --coverage"
else
  COVERAGE="--enable-coverage"
  export EXTRA_CFLAGS="-O0 --coverage"
  export EXTRA_LDFLAGS="-O0 --coverage"
fi

export MAKE_OPTS="-j5 V=1"

if [ "x$AUTOTOOLS" == "xyes" ]; then

  echo -en 'travis_fold:start:configure\r'
  autoreconf -i
  ./configure --enable-tests $COVERAGE \
    --with-sassc-dir=$SASS_SASSC_PATH \
    --with-sass-spec-dir=$SASS_SPEC_PATH \
    --prefix=$TRAVIS_BUILD_DIR
  echo -en 'travis_fold:end:configure\r'

  make $MAKE_OPTS install

  # sassc expects file to be in our root
  echo "moving libsass.a in-place for sassc"
  echo cp $TRAVIS_BUILD_DIR/lib/libsass.a $(pwd)
  cp $TRAVIS_BUILD_DIR/lib/libsass.a $(pwd)

else

  make $MAKE_OPTS $SASS_SASSC_PATH/bin/sassc

fi

script/spec
