#!/bin/bash

if [ "x$CXX" = "xg++" ]; then
  sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  sudo apt-get update -qq
  sudo apt-get install -qq g++-4.8
  sudo rm /usr/bin/cpp
  sudo rm /usr/bin/gcc
  sudo rm /usr/bin/c++
  sudo rm /usr/bin/g++
  sudo rm /usr/bin/gcov
  sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
  sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  sudo ln -s /usr/bin/c++-4.8 /usr/bin/c++
  sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  sudo ln -s /usr/bin/gcov-4.8 /usr/bin/gcov
fi
