#!/usr/bin/env node
/*jshint shelljs:true */

"use strict";

require("shelljs/make");

var path = require("path");
var JSHINT_BIN = ["node_modules", ".bin", "jshint"].join(path.sep);

exec(JSHINT_BIN + " .");
