#!/usr/bin/env node
/*jshint shelljs:true */

"use strict";

require("shelljs/make");

var path = require("path");
var mocha = ["node_modules", ".bin", "mocha"].join(path.sep);

exec(mocha + " test");
