name: Build bindings for Windows releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 14
          - 16
          - 17

        architecture:
          - x64
          - x86

        include:
          - node: 12
            os: windows-2016
          - node: 14
            os: windows-2016
          - node: 16
            os: windows-2019
          - node: 17
            os: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Install packages
        run: npm install
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v2
        if: github.repository_owner == 'sass' && github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}-${{ matrix.architecture }}
          path: |
            vendor/**/binding.node
            build/Release/binding.pdb
